#stage 1 : Creating deployabales
FROM node:latest as node
WORKDIR /app
COPY ..
RUN npm install
RUN npm run build --prod

#stage 2 : Running the angular application
FROM nginx:alpine
COPY --from=node /app/dist/angular-app /usr/share/nginx/html