#stage 1 : Creating deployabales
FROM node:latest as node
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . /app
RUN npm run build --prod

#stage 2 : Running the angular application
echo "test3"
FROM nginx:alpine
COPY --from=node /app/dist/angular-app /usr/local/Cellar/nginx/1.17.8/html
EXPOSE 80
CMD ["nginx"."g","daemon off;" ]